global:
  scrape_interval: 15s  # 15초마다 메트릭을 가져옴

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8090"]  # Spring Boot 애플리케이션의 주소