logging:
  config: classpath:logback-spring.xml
  file:
    path: /log
  level:
    "[org.springframework]": DEBUG
    "[org.mybatis]": DEBUG
    root: DEBUG    

server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cache: # Cache 설정
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:mariadb://localhost:3306/jimCarry  # 데이터베이스 URL
    username: root                                  # DB 사용자명
    password: root                                  # DB 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver     # MariaDB JDBC 드라이버
    hikari:
      maximum-pool-size: 10                         # 커넥션 풀 크기 설정


mybatis:
  type-aliases-package: com.study.jimcarry.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /index.html 
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    enabled: true
    path: /api-docs
